export type {
  OverlayConfig,
  OverlayElement,
  MapMarker,
  TelemetryPanelElement,
  MiniMapElement,
  GridElement,
  CrosshairElement,
  HeadingIndicatorElement,
  ProjectLabelElement,
  LogoElement,
  VideoMarkerElement,
  AltitudeGraphElement,
  SpeedGraphElement,
  GraphElement,
} from "@/lib/overlay/model";
